permalink: /:year-:month-:day/:title/

#highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: [
   "no_intra_emphasis"
   ,"fenced_code_blocks"
   ,"autolink"
   ,"tables"
   ,"strikethrough"
   ,"superscript"
   ,"with_toc_data"
   ,"footnotes"
   ,"highlight"
   ,"underline"
   ,"quote"
   ,"lax_spacing"
   ,"prettify"
#   ,"html_toc"
  ]
gems: ["jekyll-paginate"]


paginate: 10
paginate_path: ":num"
baseurl: ""



title: "Morgan's Blog"
email: "gnyuan@gmail.com"
description: "学无止境，记录点滴"
github_username:  "gnyuan"
weibo_url: "http://weibo.com/yuangn"
weibo_name: "MoRGaN"
swiftype_searchId: "jrgAVyFQaXaa44qtULtj"
disqus_shortname: "gnyuangithubio"



#url: "http://127.0.0.1:4000"
#imgrepo: "http://127.0.0.1:4000/static/img"
url: "http://gnyuan.github.io"
imgrepo: "http://gnyuan.github.io/static/img"


#icard setting
# Author settings
author:
  name: Morgan GN YUAN
  title: C/Java Developer
  address: Shenzhen, China
  email: gnyuan@gmail.com
  link: http://gnyuan.github.io
  weibo: http://weibo.com/yuangn 
  github: github.com/gnyuan
  linkedin: 
  twitter: 
  gavatar: /static/icard/img/avatar.JPG
  workHistory:
    - work1:
      company: ChinaClear(the financial infrasturcture of China)
      location: Shenzhen, China
      title: C/Java/RPG Developer
      started: 2014
      duration: (2014 - Present)
      description: Work at AIX, SUSE and AS400. About Communication Technology.
       1. Design and develop communication protocol between Shenzhen Stock Exchange and ChinaClear using socket.
       2. Deploy an open source process monitoring platform called RAMONA(python based) to monitor all backend process.
       3. Maintain a data deliver platform called 'D-COM' among ChinaClear and Clearing participators(Brokerage, Fund, Custodian Bank) using Java and relevant middle-wares.
       4. Make ETL process, genearate daily report from raw stock data using Java and Python.
    - work2:
      company: Baidu Inc.
      location: Beijing, China
      title: Data Analysis Intern
      started: 2013
      duration: (2013 - 2014)
      description: Mining Search Log to improve search engine and monitor effect of new features.
       1. Make ETL process from raw log to generate indicators,analysis user data using Hive and MapReduce.
       2. Build models to predict user search satisfaction using machine learning platform.
  educationHistory:
    - education1:
      organization: Zhejiang University
      degree: Master
      major: Software Engineering
      started: 2012
      duration: (2012 - 2014)
      description: Research on Time Series Mining and Software Desgin.
      Winner of National Scholorship.
    - education2:
      organization: Tianjin University
      degree: Bachelor
      major: Software Engineering
      started: 2008
      duration: (2008 - 2012)
      description: Basic Computer Foundations and Software Desgin.
  languages:
    - language1:
      name: Chinese
      proficiency: Native
    - language2:
      name: English
      proficiency: Professional
    - language3:
      name: Cantonese
      proficiency: Native
  programmingSkills:
    - skill1:
      name: C/C++
      percentage: 90%
    - skill2:
      name: Python
      percentage: 90%
    - skill3:
      name: JavaScript
      percentage: 80%
    - skill4:
      name: JQuery
      percentage: 80%
    - skill5:
      name: Java/Java EE
      percentage: 80%
    - skill6:
      name: Linux/Unix
      percentage: 80%